#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso

wclean $targetType fieldBasedGradient

# ----------------------------------------------------------------- end-of-file
